botpress/studio

- CHANGELOG.md
- package.json
- packages/studio-be/src/core/dialog/flow/flow-service.ts
- packages/studio-be/src/core/security/router-security.ts
- packages/studio-be/src/debug.ts
- packages/studio-be/src/sdk/botpress.d.ts
- packages/studio-be/src/studio/internal-router.ts
- packages/studio-ui/src/web/views/FlowBuilder/diagram/TriggerEditor/Condition/Editor.tsx
- packages/studio-ui/src/web/views/Nlu/intents/LiteEditor.tsx
> chore(studio): bring changes

- .gitignore
- packages/studio-ui/src/web/actions/index.ts
Fix the UI bug in the studio UI when the memory flow is being opened.
closes #24
> fix(studio): content elements are changed bug when node is being clicked

- packages/studio-ui/src/web/reducers/flows.ts
Fix issue where links between nodes could not be deleted on the flow editor.
fixes: https://github.com/botpress/studio/issues/60
reverts: https://github.com/botpress/studio/pull/21
> fix(studio): delete nodes link issue

- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/translations/es.json
- packages/studio-ui/src/web/translations/fr.json
- packages/studio-ui/src/web/views/Config/index.tsx
As a bot developer, I want to see my bot id on my bot settings.
> feat(config): Add bot id as readonly on bot config

- package.json
> chore(studio): bump studio to v0.0.34

- CHANGELOG.md
- package.json
* **studio:** fix session storage with storage utils ([#22](https://github.com/botpress/studio/issues/22)) ([b292015](https://github.com/botpress/studio/commit/b2920157aacc9ef2ac1d386fb7c67656e0c3e78a))
* **studio:** retry set studio ready call ([#105](https://github.com/botpress/studio/issues/105)) ([8ff62bb](https://github.com/botpress/studio/commit/8ff62bbf21f891cca959d48be2cc3e5c8830f2d7))
> chore(dev): v0.0.37

- packages/studio-be/src/core/logger/persister/console-logger.ts
- packages/studio-be/src/sdk/botpress.d.ts
> chore(dev): fix logger warnings

- CHANGELOG.md
- package.json
This adds the missing changelogs from the last release.
> chore(dev): added missing changelog

- packages/studio-be/src/builtin/actions/basic-skills/slot_update_contexts.js
- packages/studio-be/src/core/dialog/skills/slot.ts
brings back these changes from the master branch of the main repo: [#5573](https://github.com/botpress/botpress/pull/5573).
> fix(basic-skills): slot filling issues if using validation function

- packages/studio-ui/src/web/components/Layout/BottomPanel/index.tsx
- packages/studio-ui/src/web/components/Layout/BottomPanel/style.scss
- packages/studio-ui/src/web/components/Layout/BottomPanel/style.scss.d.ts
This adds common buttons to code editor on bottom panel
New view
> feat(bottomPanel): add common button on code editor

- packages/studio-be/src/studio/nlu/entities-service.ts
- packages/studio-be/src/studio/nlu/intent-service.ts
- packages/studio-be/src/studio/nlu/nlu-router.ts
- packages/studio-ui/src/web/views/Nlu/entities/EntityNameModal.tsx
- packages/studio-ui/src/web/views/Nlu/entities/ListEntity.tsx
- packages/studio-ui/src/web/views/Nlu/entities/PatternEntity.tsx
- packages/studio-ui/src/web/views/Nlu/entities/SidePanelSection.tsx
- packages/studio-ui/src/web/views/Nlu/entities/entity-id.ts
- packages/studio-ui/src/web/views/Nlu/index.tsx
Closes DEV-1389
Fixes: https://github.com/botpress/botpress/issues/5155
> fix(nlu): prevent creating an entity with same name as a system

- packages/studio-ui/src/web/views/Nlu/intents/UtterancesEditor.tsx
- packages/studio-ui/src/web/views/Nlu/intents/utterances-state-utils.ts
Closes: DEV-1392
Fixes: https://github.com/botpress/botpress/issues/5159
This fix made me wanna stop coding and start a career as a lumberjack. Slate is a mess.
Here's the result:
https://user-images.githubusercontent.com/25970722/139730178-f710396f-b86e-4570-84fa-99dc2c232ffe.mov
> fix(nlu): allow copy paste utterances

- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/translations/fr.json
- packages/studio-ui/src/web/views/FlowBuilder/sidePanelFlows/FlowNameModal.tsx
Fixes https://linear.app/botpress/issue/DEV-1425/[bug]-flow-editor-skills-folder-is-nowhere-botpressstudio-43
> fix(studio): prevent using skills in folde rname

- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/translations/es.json
- packages/studio-ui/src/web/translations/fr.json
- packages/studio-ui/src/web/translations/index.tsx
- packages/studio-ui/src/web/views/FlowBuilder/inspector/index.tsx
Fixes: https://github.com/botpress/studio/issues/177
Closes: DEV-1965
looks so nice now:
> fix(studio): added translations in node and flow inspector

- packages/studio-ui/src/web/reducers/flows.ts
Fixes https://github.com/botpress/botpress/issues/5132
> fix(studio): incorrect transition migration after updating skill

- packages/studio-ui/src/web/components/Authentication/index.jsx
https://linear.app/botpress/issue/DEV-1414/[feature]-remove-default-auto-logout-botpressbotpress-5272 
Related to this but not this. It's a new issue. The user gets logged out without the studio responding in time. The studio checks every 60 seconds, but that can be an eternity, when there's an error message without an explanation.
> Fix(studio):  handles logout gracefully

- packages/studio-ui/src/web/components/Authentication/index.jsx
- packages/studio-ui/src/web/views/FlowBuilder/index.tsx
Small UI fixes for https://github.com/botpress/studio/pull/185
> fix(studio): more time for logging that user is logged out

- packages/studio-ui/src/web/views/Nlu/intents/utterances-state-utils.ts
Bug was created during the x-games in this PR: 
https://github.com/botpress/studio/pull/171/files#diff-932f258625ec885af9a1d0f5c5f0799779e8c3e71b074c7fee82903142f72f74R51
> fix(studio): fix regression in utterance parsing

- CHANGELOG.md
- package.json
- packages/studio-ui/src/web/components/Layout/Toolbar/index.tsx
- packages/studio-ui/src/web/components/Layout/Toolbar/style.scss
- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/translations/es.json
- packages/studio-ui/src/web/translations/fr.json
> feat(toolbar): Add CTA button

- packages/studio-be/src/core/distributed/async-redis.ts
Same thing as https://github.com/botpress/botpress-pro/pull/62 and https://github.com/botpress/messaging/pull/258
> fix(redis): fix redis only retrying to connect 10 times

- packages/studio-be/src/sdk/botpress.d.ts
- packages/studio-be/src/studio/nlu/application/bot-factory.ts
- packages/studio-be/src/studio/nlu/application/bot/index.ts
- packages/studio-be/src/studio/nlu/application/typings.ts
- packages/studio-be/src/studio/nlu/nlu-service.ts
- packages/studio-ui/src/web/components/Layout/StatusBar/TrainingStatus/SingleLang.tsx
- packages/studio-ui/src/web/components/Shared/Utils/Toaster.tsx
Fixes: https://github.com/botpress/nlu/issues/69
Fixes: DEV-1446
> feat(nlu): report training errors in the studio

- .eslintrc.js
> chore(dx): fix eslint check

- packages/studio-be/package.json
- packages/studio-be/scripts/copy_builtin.js
This PR fixes e2e tests on branch next of the main repo: https://github.com/botpress/botpress/pull/5747
> chore(dx): copy builtin on build

- packages/studio-ui/src/web/views/Nlu/entities/ListEntity.tsx
- packages/studio-ui/src/web/views/Nlu/entities/ListEntityOccurrence.tsx
fixes DEV-1217
fixes https://github.com/botpress/botpress/issues/4446
> fix(nlu): trim entity occurences on change

- packages/studio-be/src/studio/nlu/application/bot-factory.ts
- packages/studio-be/src/studio/nlu/application/nlu-client/cloud/client.ts
title says it all
goes in hand with: https://github.com/botpress/botpress/pull/5750
closes DEV-2027
> feat(nlu): use cloud nlu when cloud config is set

- packages/studio-ui/src/web/components/Layout/StatusBar/index.tsx
- packages/studio-ui/src/web/components/Layout/StatusBar/style.scss
- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/translations/es.json
- packages/studio-ui/src/web/translations/fr.json
Adds `Cloud Enabled Chatbot` to the status bar for cloud enabled chatbots
> feat(statusbar): cloud enabled status

- packages/studio-ui/src/web/components/Layout/Layout.scss
- packages/studio-ui/src/web/components/Layout/index.tsx
- packages/studio-ui/src/web/views/FlowBuilder/style.scss
- packages/ui-shared/src/MainLayout/Wrapper/style.scss
Before
https://user-images.githubusercontent.com/159949/149004132-413dd269-f6c3-4c98-bf7a-949406071d77.mov
After
https://user-images.githubusercontent.com/159949/149004146-35e02dcb-a0d7-4ce3-8d8f-3db1446e0331.mov
> fix(layout): bottom panel maintain size

- packages/studio-be/src/core/dialog/flow/flow-service.ts
I inverted the condition in refactor
> fix(flow): reverse flow name condition

- CHANGELOG.md
- package.json
> chore(dev): 0.0.46

- packages/studio-be/src/core/bots/bot-service.ts
- packages/studio-be/src/core/bpfs/ghost-service.ts
Basically same as https://github.com/botpress/botpress/pull/11218/files
> fix(internal-router): make chatbot creation fast again

- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/components/Settings.tsx
- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/index.tsx
- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/views/NLU.tsx
- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/views/Processing.tsx
- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/views/Summary.tsx
fixes: DEV-219
https://user-images.githubusercontent.com/25970722/151442001-a13eef9f-bf6a-4251-9c74-f546313979a1.mov
> fix(ui): no model warning in debugger only appears when there's no model

- .github/workflows/pre-release.yml
Already made the change to next
> chore(workflow): always run build workflow

- .github/workflows/build.yml
- .github/workflows/codestyle.yml
- .github/workflows/delete-pre-release.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
This PR improves the current actions by adding caching, removing unnecessary steps, renaming some actions, and adding new actions like build and test.
Note that the unit tests will fail and be fixed in another PR.
> chore(ci_cd): improve and add new actions

- .github/workflows/delete-pre-release.yml
Fix issue with delete pre-release actions that were introduced here: https://github.com/botpress/studio/pull/267
> chore(ci_cd): fix delete pre-release bins

- .github/workflows/codestyle.yml
- .github/workflows/delete-pre-release.yml
- .github/workflows/pre-release.yml
Adds missing improvements to some actions like adding `--immutable` to yarn when installing deps or not running some actions when dependabot opens PRs
> chore(ci_cd): add missing improvements to actions

- CHANGELOG.md
- package.json
> chore(server): v0.0.47

- packages/studio-ui/src/web/components/Content/Select/Manager.tsx
The content picker was broken since https://github.com/botpress/studio/pull/279
> fix(studio): content picker broken

- packages/studio-ui/src/web/components/Layout/StatusBar/Flag.tsx
- packages/studio-ui/src/web/components/Layout/StatusBar/LangSwitcher.tsx
- packages/studio-ui/src/web/components/Layout/StatusBar/style.scss
rewrite of language switcher with common dropdown.  I'm aware style isn't exactly the same but I believe it's good enough as it touches a tiny portion of the user base.
If you guys don't agree, you are welcome on styling this thing.
@sebburon should fix your issue
Closes https://github.com/botpress/botpress/issues/11405
> chore(layout): use bp3 dropdown for lang switcher

- packages/studio-ui/src/web/views/Qna/style.scss
Strangely the qna questions doesn't scroll and you need to filter to find the right one to change... 
Before
After
> fix(qna): fix scrolling

- CHANGELOG.md
- package.json
New release of the studio In anticipation of releasing Botpress soon
> chore(server): v0.0.48

- packages/studio-be/src/builtin/actions/basic-skills/slot_update_contexts.js
fixes: DEV-2361
fixes learn botpress bot template
> fix(studio-be): slot skill points calls correct url

- packages/studio-be/src/builtin/content-types/card.ts
PR https://github.com/botpress/studio/pull/304 broke the card and carousel (impossible to add new actions). Slight fix
> fix(studio): fix card and carousel

- packages/studio-ui/src/web/views/CodeEditor/Editor.tsx
- packages/studio-ui/src/web/views/CodeEditor/utils/wrapper.ts
Brought the changes from the code editor module. fixes the readonly stuff
> fix(next): code editor read only bot config

- packages/studio-be/src/common/code-editor.ts
- packages/studio-ui/src/web/views/CodeEditor/components/NewFileModal.tsx
- packages/studio-ui/src/web/views/CodeEditor/utils/wrapper.ts
Bringing back changes from there:
https://github.com/botpress/botpress/pull/11598
> fix(code-editor): minor ux fixes

- CHANGELOG.md
- package.json
> chore(server): v0.0.49

- CHANGELOG.md
- package.json
- packages/studio-be/src/migrations/v12_26_13-1652113646-migrate_messaging_creds.ts
- packages/studio-be/src/migrations/v12_26_13-1652113646-migrate_messaging_creds_on_import.ts
Adds a migration for https://github.com/botpress/botpress/pull/11646
> chore(migration): migration for srv_channels

- packages/studio-be/src/builtin/actions/builtin/getNumberOfConversations.js
- packages/studio-be/src/builtin/actions/builtin/incrementNumberOfConversations.js
Fixes the number of conversations actions to use scoped kvs. This will make the welcome bot work correctly on the runtime
Closes DEV-2520
> fix(actions): fix number of conversations action

- packages/studio-be/src/index.ts
- packages/studio-be/src/studio/cloud/cloud-router.ts
- packages/studio-be/src/typings/global.d.ts
This PR makes sure to bring changes made here https://github.com/botpress/botpress/pull/11676 to the studio
> chore(core): use proper env var for controller endpoint

- packages/studio-be/src/index.ts
- packages/studio-be/src/sdk/botpress.d.ts
- packages/studio-be/src/sdk/botpress.runtime.d.ts
- packages/studio-be/src/studio/cloud/cloud-router.ts
- packages/studio-be/src/studio/nlu/bot-factory.ts
- packages/studio-be/src/studio/nlu/nlu-client/cloud/client.ts
- packages/studio-be/src/typings/global.d.ts
> fix(dev): local cdm setup

- packages/studio-be/src/studio/cloud/cloud-router.ts
- packages/studio-ui/src/web/components/Layout/TopNav/DeployCloudBtn.tsx
- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/translations/es.json
- packages/studio-ui/src/web/translations/fr.json
When runtime on the CloudFormation stack isn't ready, error message isn't clear that this issue might take some time to resolve.
Make it clear
> feat(deploy): deploy to cloud btn should show failure toaster if runtime not ready

- packages/studio-ui/src/web/views/FlowBuilder/sidePanelFlows/index.tsx
Fixes https://github.com/botpress/studio/issues/289
Closes DEV-2327
> fix(ui): toggle explorer

- packages/studio-be/src/index.ts
Fixing url so its the same as the main repo
> fix(studio): fix cloud url (same as main repo)

- packages/studio-be/src/studio/studio-router.ts
- packages/studio-ui/src/web/index.jsx
> fix(ui): redirect to admin on init error

- packages/studio-ui/src/web/index.jsx
This little PR ensures that the token is used to perform the /env call otherwise we get a redirect for sure. I have no idea how this could've worked out in the first place
> fix(studio-ui): fix redirect even when authorized

- CHANGELOG.md
- package.json
> chore(studio): bump studio to v0.0.57

- packages/studio-ui/src/web/components/Layout/TopNav/DeployCloudBtn.tsx
- packages/studio-ui/src/web/components/Layout/TopNav/cloud/Step3-deploy.tsx
Now closes the popup if the upload fails
https://www.loom.com/share/15d204f1068c474c91b2cf0c06ba6785
> fix(cloud): close popup when upload fails

- packages/studio-ui/src/web/views/FlowBuilder/common/ContentItem.tsx
undefined check to prevent this error:
> fix(studio): studio crash on undefined content item

- packages/studio-ui/src/web/views/FlowBuilder/diagram/nodes/Block/index.tsx
> fix(studio): allow context menu on non default language
