- package.json
- packages/studio-be/src/core/app/botpress.ts
- packages/studio-be/src/core/app/inversify/app.inversify.ts
- packages/studio-be/src/core/logger/persister/console-logger.ts
- packages/studio-be/src/core/logger/persister/db-persister.ts
Added db logger so we have logs on the admin panel..
> fix(studio): add db logger

- packages/studio-ui/package.json
- packages/studio-ui/src/web/components/ContentForm/UploadWidget/index.tsx
- packages/studio-ui/src/web/components/ContentForm/index.tsx
- packages/studio-ui/src/web/components/ContentForm/typings.ts
- packages/ui-shared/src/FileDisplay/index.tsx
- packages/ui-shared/src/FileDisplay/style.scss
- packages/ui-shared/src/FileDisplay/style.scss.d.ts
- packages/ui-shared/src/Form/FormFields/typings.d.ts
- packages/ui-shared/src/typings.d.ts
- yarn.lock
This PR adds the ability to display help/hints under form fields. Also contains some changes that were missing from: https://github.com/botpress/botpress/pull/5045
Related to this PR: https://github.com/botpress/botpress/pull/5131
> feat(studio): add support for help/hints with content form

- packages/studio-ui/src/web/components/SmartInput/index.tsx
Currently the text editor aligns the text to the left for RTL languages, switching that to the right when the arabic language is selected
> chore(studio): Right indent text in Arabic language

- packages/studio-be/package.json
- packages/studio-be/src/core/bpfs/drivers/disk-driver.ts
- yarn.lock
This PR fixes an issue where a race condition may happen on slow storage disks when using BPFS_STORAGE=disk.
Related PR in main repo: https://github.com/botpress/botpress/pull/5162
The issue is similar to what is shown in this thread: https://stackoverflow.com/questions/57303480/writing-to-a-file-and-simultaneously-reading-it-to-create-a-race-condition-in-no
1. Use a slow HDD or a slow/old USB stick.
2. Mount out/bp/data to the USB device (or HDD).
3. Start Botpress
4. Create an empty bot and add two text content-element to the entry node.
5. Open the Chrome inspector.
6. Move the entry node so that it sends a flow update request.
7. Open Postman and replicate the flow update POST request
8. Use Postman's runner (bottom right) to execute the request ~1000 times
9. You should see the error …
> fix(core): fix disk storage race condition

- packages/ui-shared/src/Toaster/index.tsx
Made some UI modifications for the Toaster. Here are the before and after screenshots to detail the changes: 
Before: 
After:
> fix(studio): UI toast modifications

- packages/studio-ui/src/web/components/Shared/Utils/index.tsx
- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/translations/es.json
- packages/studio-ui/src/web/translations/fr.json
- packages/studio-ui/src/web/views/FlowBuilder/sidePanelFlows/FlowsList.tsx
- packages/studio-ui/src/web/views/FlowBuilder/sidePanelFlows/util.tsx
Should be merged so the new flow has a custom icon like the others.
Related to this PR https://github.com/botpress/botpress/pull/5215
> feat(studio): Custom Icon for Conversation End Flows

- packages/studio-ui/src/web/reducers/flows.ts
I created a PR for this issue #20.
If a linked node is renamed, the link between the source and the output is removed  
https://user-images.githubusercontent.com/6981314/128202726-3e6f3fd6-2fc1-4435-a29f-8acc36f32df6.mov
> fix(studio) Renamed node is deconnected from the parent node 

- packages/studio-ui/src/web/views/FlowBuilder/diagram/index.tsx
There was an annoying issue - when a user moves a node, it opens up a node props on the right. I added a check - if the note has been moving or not, and so I disable the props in the first case.
> fix(studio): don't open node props when moving it

- packages/studio-ui/src/web/components/Layout/Sidebar.tsx
Users often tend to navigate to 'content' instead of 'flow' as a default human reflex.
Since "Flow" is our main working entity in studio, swapping these items will improve UX by making first item as "Flows"
> fix: Swapped flow and content menu items in side menu

- packages/studio-ui/src/web/components/Content/Select/Widget.tsx
- packages/studio-ui/src/web/components/Content/Select/index.tsx
- packages/studio-ui/src/web/components/Content/Select/style.scss
- packages/studio-ui/src/web/components/Content/Select/style.scss.d.ts
I'm not trying to redo the whole content picker because that would take a lot of time. 
This aims only to get rid of the issue I got where I was writing text, then "create new text" appears greyed out, and I subconsciously decided it was created, then clicked x and nothing appeared. :(
The fix lies in adding the "active" state to "create new ${content_type}" when there are no search results, to make it more obvious, and having the "enter" key create or select whatever is active
This also makes it so clicking the greyed out bar acts as create / update button, not just the icon, because I was clicking that too!
> fix(studio) content picker confusion

- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/components/Intent.tsx
- packages/studio-ui/src/web/components/Layout/GuidedTour.jsx
- packages/studio-ui/src/web/components/Layout/Sidebar.tsx
- packages/studio-ui/src/web/components/Layout/Toolbar/index.tsx
- packages/studio-ui/src/web/components/Layout/index.tsx
- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/views/FlowBuilder/diagram/index.tsx
Guided tour now highlights correct array. It was highlighting nothing for a few nodes and staying in the middle. I removed the bubble, and updated the text to make it slightly less challenging to read. 
When right clicking in the flow UI, then clicking on the "skill" submenu button, the menu would close. This is a problem when you move around / click around too fast. 
This no longer happens. :)
Finally, there was a soft-crash happening when the user clicked the top intents 
It now redirects as it should.
> fix(studio): guided tour highlighting restored and more

- packages/ui-shared/src/Dialog/style.scss
Reverts part of code that caused this overflowing issue.
> Reverts overflow behavior. Fix overflowing content

- packages/studio-be/src/core/migration/bot-migration-service.ts
- packages/studio-be/src/core/migration/migration-service.ts
- packages/studio-be/src/migrations/v12_21_1-1618260400-bot_content_type_update.ts
Bot migrations were not taking into account TESTMIG_NEW or TESTMIG_ALL, so it was not in sync with the core. Simple fix, copied the logic from core.
> fix(studio): bot mig same behavior as core

- packages/studio-be/src/common/typings.ts
- packages/studio-be/src/core/cms/cms-service.ts
- packages/studio-be/src/studio/cms/cms-router.ts
- packages/studio-ui/package.json
- packages/studio-ui/src/web/components/Content/Select/index.tsx
- packages/studio-ui/src/web/components/Layout/CommandPalette.tsx
- packages/studio-ui/src/web/reducers/content.ts
- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/translations/es.json
- packages/studio-ui/src/web/translations/fr.json
- packages/studio-ui/src/web/views/Content/SideBar.tsx
- packages/studio-ui/src/web/views/Content/index.tsx
- packages/studio-ui/src/web/views/FlowBuilder/diagram/nodes/SaySomethingContents/index.tsx
- packages/studio-ui/src/web/views/FlowBuilder/sidePanelTopics/form/SaySomethingForm.tsx
- packages/ui-shared/src/translations/en.json
- packages/ui-shared/src/translations/es.json
- packages/ui-shared/src/translations/fr.json
- yarn.lock
This PR adds support for editing content-elements event when at least one of the bot's content-types are unregistered. It also displays the list of unregistered content-types.
When you had an unregistered content-type, you would get this error on the CMS page:
Closes DEV-1519
> fix(cms): display unregistered content-types instead of error message

- packages/studio-ui/src/web/views/Config/index.tsx
**Descriptiion:**
When saving the bot configuration, there is an error 
(image below)
The bot id is a readonly input and I just removed it from the bot error config...
now we have
> fix(studio-ui): remove id from bot form parameters

- packages/studio-be/src/common/typings.ts
- packages/studio-ui/src/web/components/Content/Select/Widget.tsx
- packages/studio-ui/src/web/views/FlowBuilder/nodeProps/ActionModalForm.tsx
- packages/studio-ui/src/web/views/FlowBuilder/nodeProps/ParametersTable.tsx
This PR fixes an issue where upon attempting to add multiple actions, the action parameters would not be reset
https://user-images.githubusercontent.com/9640576/132726343-d7f4a345-6b29-4019-977b-479571b86ba3.mp4
https://user-images.githubusercontent.com/9640576/132726351-11d329cf-57a2-44bf-a0e3-e9de42000d92.mp4
Closes #5213
Closes DEV-1401
> fix(flow): fix clearing node action parameters on close

- .github/workflows/branch_deleted.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
Each time something is pushed on a branch, a binary is built and a "pre-release" is created with the binaries. Those binaries can be downloaded by the downloader on the main repo. 
Had to change the "latest tag" logic, because even if a tag is a pre-release, it was counted as an official tag
> feat(dev): binary branches

- .github/workflows/branch_deleted.yml
- .github/workflows/pre-release.yml
- packages/studio-be/src/core/app/bootstrap.ts
- packages/studio-be/src/index.ts
- packages/studio-be/src/typings/global.d.ts
I often lose time trying to find out why something doesn't work, to find out that I'm running a binary or that i'm not on the correct branch... So i'm adding some logic to help with the dx: 
- If the code is executed from source (versus a custom binary), it will add a small label telling so
- If it's a binary which has been built from a specific branch, the name will also be displayed
This doesn't affect the official binary, which will still display only the version like before.
> fix(studio): add developer cue

- packages/studio-ui/src/web/components/SmartInput/index.tsx
- packages/studio-ui/src/web/components/SmartInput/styles.scss
- packages/studio-ui/src/web/translations/index.tsx
- packages/studio-ui/src/web/views/Config/index.tsx
- packages/studio-ui/src/web/views/FlowBuilder/common/action.tsx
- packages/studio-ui/src/web/views/FlowBuilder/common/condition.jsx
- packages/studio-ui/src/web/views/FlowBuilder/diagram/nodes/BaseNodeModel.tsx
- packages/studio-ui/src/web/views/FlowBuilder/diagram/nodes/Components/NodeHeader.tsx
- packages/studio-ui/src/web/views/FlowBuilder/diagram/nodes/StandardContents/index.tsx
This PR is about fixing known issues after merging [this PR](https://github.com/botpress/studio/pull/61)
The issue : The *WaitOn user input* is always displayed.
The solution: 
- I reverted the RTL updates 
- I also removed unnecessary props from the store
- I fetched the contentLang from the store on the Node component (cause of the issue) directly from the store object. 
(below how it looks like now)
> fix(flowbuilder): fix wait on issue with new rtl procedure

- packages/studio-be/src/core/app/core-client.ts
I was able to reproduce the bug where the studio would be ready before the runtime server by placing a Promise.delay somewhere. This fix prevents the studio from crashing with a ECONNREFUSED error and just keeps retrying to inform the runtime that it is ready.
The fix works, but I'm not really sure why we start the studio before the runtime server is started. Maybe a better fix in the future would be to boot the runtime completely and then start the studio
Closes DEV-1470
> fix(studio): retry set studio ready call

- packages/studio-ui/src/web/views/Qna/Components/QnA.tsx
- packages/studio-ui/src/web/views/Qna/style.scss
- packages/ui-shared-lite/MoreOptions/MoreOptionsMenu.tsx
- packages/ui-shared-lite/MoreOptions/index.tsx
- packages/ui-shared-lite/MoreOptions/style.scss
- packages/ui-shared-lite/MoreOptions/style.scss.d.ts
- packages/ui-shared-lite/MoreOptions/typings.d.ts
The issue is easily reproductible. I thought it was a z-index thing but turns out z-index don't apply to `position:relative` elements. Removing that position relative statement had me play around with a bunch of styles. In the end, there is no visible change except the actual fix (see screencaps)
Before  :
After:
Closes https://github.com/botpress/botpress/issues/5417 DEV-1693
> fix(qna): fix language dropdown overlay issue 

- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/views/Summary.tsx
- packages/studio-ui/src/web/views/FlowBuilder/diagram/debugger.ts
Fix when state is missing (eg: message sent when not authenticated).
> fix(studio): error when state missing in debugger

- packages/studio-be/src/studio/libraries/libraries-router.ts
- packages/studio-ui/src/web/components/Layout/Sidebar.tsx
Users with bot.nlu permissions were able to play around with libraries... moved the perms with the code editor
> fix(studio): fix permissions for libraries

- packages/studio-ui/src/web/views/FlowBuilder/nodeProps/ActionModalForm.tsx
This PR fixes an issue where it was possible to add empty actions to a node. To fix this issue, a validation was added to make sure the form is valid before enabling the submit button.
**Before**
https://user-images.githubusercontent.com/9640576/134557976-7e5ce35f-d8a4-416d-8d86-5a126bbf86d6.mp4
**After**
https://user-images.githubusercontent.com/9640576/134557986-284807fd-f5d8-41d4-a882-4cf1e196edaf.mp4
Closes #76 and DEV-1638
> fix(studio): prevent creating empty actions

- packages/studio-be/src/sdk/botpress.d.ts
- packages/studio-ui/src/web/actions/index.ts
- packages/studio-ui/src/web/components/Content/Select/index.tsx
This PR fixes an issue where when editing a selected content-element in a node, it would not let you change the content-type. The option was only provided when adding a content-element.
**Before**
https://user-images.githubusercontent.com/9640576/134696550-3cf39f59-4c03-48ec-96a6-930489a98284.mp4
**After**
https://user-images.githubusercontent.com/9640576/134696270-1c18a5a0-c774-4da2-946f-05ba9893ddfc.mp4
Closes https://github.com/botpress/botpress/issues/5334
Also closes DEV-1535
> fix(studio): allow changing content-type when editing node content-element

- .gitignore
- .vscode/launch.json
- gulpfile.js
- package.json
- scripts/gulp.env.debug.js
- yarn.lock
This PR does 2 things:
1. adds a launch.json file for debugging
2. create a default, git-ignored, `.env.debug` file to be used by `launch.json`
The `.env.debug` file allows a developer to change debug config without having to modify the git tracked `launch.json`
> chore(dx): added a default env file used in launch.json file for debugging

- packages/studio-ui/src/web/views/FlowBuilder/index.tsx
This PR fixes a translation when pressing Ctrl + S on the flow editor
**Before**
**After**
Closes #99
And closes DEV-1705
> fix(flow): fix ctrl + s toast text display

- packages/ui-shared-lite/Collapsible/index.tsx
The `toggleExpand` prop isn't always defined and is listed as optional in the typing, this causes a bug in HITL next
> fix(ui-shared): Fix collapsible toggleExpand undef

- packages/studio-ui/src/web/views/Config/index.tsx
This PR fixes an issue where it was possible to set a bot name with more than 50 chars which isn´t valid and throws a validation error in the front-end
Related to: https://github.com/botpress/botpress/pull/5524
> fix(studio): added form validation to bot settings page

- packages/studio-ui/src/web/views/Qna/Components/QnA.tsx
- packages/studio-ui/src/web/views/Qna/Components/TextAreaList.tsx
- packages/ui-shared/src/Textarea/index.tsx
- packages/ui-shared/src/Textarea/typings.d.ts
fixes #130 
We base ourselves on content language
Preview:
Waiting on confirmation from an arabic speaker to see if display is correct
> fix(qna): add RTL content language support

- packages/studio-ui/src/web/views/FlowBuilder/utils/general.util.ts
Fixes issue #104 
And closes DEV-1913
The problem was relying upon a regex that didn't match underscore. 
Before 
After : 
And in botpress : 
https://user-images.githubusercontent.com/9640576/139689566-dfdfeda8-6122-4a30-a893-de0bd2afed40.mp4
> Fixed regex for matching text and _ 

- packages/studio-ui/src/web/views/FlowBuilder/nodeProps/ConditionModalForm.jsx
Linear issue: DEV-1260
This fixes https://github.com/botpress/botpress/issues/4571 
https://www.awesomescreenshot.com/video/5854955?key=8bdc26c0b9070f9c41ed66f19e42f1a9
Fix is to save a new field in the `flow.json` named `conditionType` instead of inferring it at load time. 
New `Flow.json` : 
Note: The one transition added with this new behavior has a `"conditionType": "raw"` field. 
It is not breaking and backward compatible. 
Note 2 : 
This does not migrate actions! 
The old behavior was : "Create a raw action" => "Type is badly inferred to MatchedProps" 
New behavior: "Create a raw action" => "Save it and load it as raw action"
New behavior for old actions "Load it: as there is no `conditionType` infer type (e.g load a MatchedProps), save it as MatchedProps". If the user wanted to …
> fix: CallAPI Transition Edit Not Persisted

- README.md
- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/views/Summary.tsx
Closes DEV-5465
Closes https://github.com/botpress/botpress/issues/5465
from the original issue screenshot a null check was missing.  
Inspecting messages works fine.
> fix(debugger): Voice-Content Type in Emulator

- README.md
- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/views/Dialog.tsx
This PR fixes a missing translation in the debugger
Fixes https://github.com/botpress/studio/issues/169
Closes DEV-1961
**Before**
**After**
> chore(debugger): fix missing translation

- packages/studio-ui/src/web/views/FlowBuilder/nodeProps/ActionModalForm.tsx
- packages/studio-ui/src/web/views/FlowBuilder/nodeProps/ParametersTable.tsx
Closes: DEV-1371
Fixes: https://github.com/botpress/botpress/issues/5107
When changing an action to a new action, the completed fields are lost.
> fix(studio): Node Action overwrite flushing data

- README.md
- packages/studio-ui/src/web/views/Nlu/intents/ContextSelector.tsx
Closes DEV-1963
Closes https://github.com/botpress/botpress/issues/5638
Fix was to add the missing value parameter in `tr()`
> fix: hardcoded query in context dropdown

- packages/studio-be/src/core/bots/bot-service.ts
- packages/studio-be/src/core/dialog/flow/flow-service.ts
- packages/studio-be/src/index.ts
When you delete a bot, flows in the studio are not cleared correctly so they stayed in memory and were displayed if you re-created a bot with the same id.
This is a quick workaround to cleanup correctly 
Fixes https://linear.app/botpress/issue/DEV-1670/[bug]-deleted-bots-not-being-deleted-properly-botpressbotpress-5393****
> fix(studio): no ghost flows when deleting a bot

- packages/studio-ui/src/web/views/FlowBuilder/nodeProps/parameters.scss
- packages/ui-shared/src/Dialog/style.scss
https://linear.app/botpress/issue/DEV-1956/[bug]-ui-issue-when-using-multiple-arguments-in-an-action
This PR requires a fix in the main repo as well  (PR coming)
> fix(skills): dialog overflow on too many params, fixes #149

- packages/studio-ui/src/web/components/ContentForm/Text.tsx
- packages/studio-ui/src/web/components/SmartInput/index.tsx
fixes #49
https://linear.app/botpress/issue/DEV-1429/[bug]-typing-opening-braces-causes-jump-in-caret-botpressstudio-49
This was happening in a very specific scenario.. which is when you use the SmartInput in a content form of type Text (but not array).  This happened for the basic/text content-type.
> fix(studio): fix the smartinput suggestions cursor in contentform

- packages/studio-ui/src/web/views/Content/List.tsx
fixes #139 
https://linear.app/botpress/issue/DEV-1911/[bug]-cms-not-loading-when-zh-language-is-selected-botpressstudio-139
When you add a new language to a bot then try to load the CMS in that new language, the CMS will fail to render.
This happens because the CMS needs to refresh the content elements for that bot after saving the config.
Although this PR fixes it, a more robust fix that would prevent restarting the server would be to invalidate the CMS.. but it didn't seem necessary IMO as this seems to be the only place where it crashes and it fixes it.
> fix(studio): CMS crashes on new language translation

- packages/studio-ui/src/web/components/Layout/index.tsx
The emulator webchat is displayed by default instead of hidden by default.. which makes more sense for new users
> fix(studio): show webchat by default

- packages/studio-ui/src/web/views/FlowBuilder/inspector/index.tsx
https://linear.app/botpress/issue/DEV-1421/[bug]-link-between-node-is-deconnected-when-a-node-is-renam
https://user-images.githubusercontent.com/6981314/139719808-52ab210f-f53b-4676-91aa-9f0e59184e49.mov
e
> DEV-1421: Fix rename node

- packages/studio-ui/src/web/components/Layout/index.tsx
If you resized the debugger panel then came back in a smaller window size, the panel would be out of the screen and impossible to get back without clearing your localStorage.
This happened to me all the time...
> fix(studio): can't lose the bottom debugger panel because of window resize anymore

- packages/studio-be/src/sdk/botpress.d.ts
- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/views/NLU.tsx
- packages/studio-ui/src/web/components/Layout/BottomPanel/index.tsx
- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/translations/es.json
- packages/studio-ui/src/web/translations/fr.json
When you have no NLU model trained and you use the webchat, it was difficult to know why the predicted intent was "None".. this confused some users in the past. 
I made it obvious that when no NLU model was used for the prediction, that we display an error in the Debugger in the Language Understanding section.
**This branch depends on the `sp_no_nlu` branch in botpress/botpress**
> fix(studio): display error when no nlu modelId

- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/views/Dialog.tsx
There was a missing translation in the debugger that didn't look professional and bugged me for a while.
> fix(studio): missing translation in debugger panel

- packages/studio-be/src/common/url.ts
- packages/studio-be/src/core/media/providers/ghost-media-service.ts
Fixing the paths when `EXTERNAL_URL` is set
Fixes # Issue 1034 on Linear
Please delete options that are not relevant.
Depends on pull request on Botpress/botpress
> dev-1034 Part 1: subdomain media URL

- packages/studio-ui/src/web/components/ContentForm/UploadWidget/UrlUpload.tsx
- packages/studio-ui/src/web/translations/en.json
(the warning message is added)
Really simple. Doesn't attempt to standardize everything, but instead warns user when content requires triple braces. 
The use case is when a user gets an image / file / video link from somewhere, and needs to display it.
> fix(studio): warns user about double braces

- packages/studio-ui/src/web/components/ContentForm/UploadWidget/index.tsx
Tested, works now.
Caused by onChange handler disallowing an empty value in validation
Fixes https://github.com/botpress/studio/issues/140
> fix(content): fix carousel image delete button

- packages/studio-ui/src/web/components/Layout/BottomPanel/Debugger/index.tsx
This PR is related to https://github.com/botpress/botpress/pull/5591 
It changes the way new sessions are created from the debugger by posting a `new-session` message instead of a `change-user-id` one.
> chore(debugger): send new session message to debugger

- packages/studio-ui/src/web/views/Qna/Components/TextAreaList.tsx
Q&A input would create a new question when pressing enter on IME input:
https://user-images.githubusercontent.com/18604963/139714233-f6ed5c00-0588-4f55-ad81-a52e216f8ae9.mov
https://user-images.githubusercontent.com/18604963/139714266-ea6993c6-16b8-4b7b-8bb2-ba1c380d4b24.mov
Fixes https://github.com/botpress/botpress/issues/3062
> fix(qna): Stop new qna line on enter press on IME input

- packages/studio-ui/package.json
- packages/studio-ui/src/web/util/EventBus.ts
- yarn.lock
This PR bumps the socket.io library to its latest version.
> chore: bump socket.io to latest version

- packages/studio-ui/src/web/components/Content/Select/Widget.tsx
- packages/studio-ui/src/web/components/Content/Select/WidgetContext.tsx
- packages/studio-ui/src/web/components/ContentForm/ContentNotice.tsx
- packages/studio-ui/src/web/components/ContentForm/index.tsx
- packages/studio-ui/src/web/components/ContentForm/style.scss
- packages/studio-ui/src/web/components/ContentForm/style.scss.d.ts
- packages/studio-ui/src/web/components/Shared/Utils/index.tsx
- packages/studio-ui/src/web/views/Content/index.tsx
- packages/ui-shared/src/translations/en.json
- packages/ui-shared/src/translations/es.json
- packages/ui-shared/src/translations/fr.json
https://linear.app/botpress/issue/DEV-2138/add-warning-message-if-content-used-in-multiple-places
Warn users when changing CMS content that is used in multiple nodes or properties.
> feat(studio): add warning when editing shared content

- packages/studio-be/src/core/bots/bot-service.ts
https://linear.app/botpress/issue/DEV-2026/a-user-can-enter-cloud-ready-options-when-creating-a-bot-on-the-admin
Support writing `bot.config.json` with cloud-ready options
- https://github.com/botpress/typings/pull/2
- https://github.com/botpress/botpress/pull/5704
> feat(cloud): support cloud-ready options in bot config

- .github/workflows/pre-release.yml
Alright, this is my take on improving the prerelease GH task.
If you toggle between "draft" and "ready for review" you'll see that the action gets canceled and started accordingly.
Also, you'll notice that `${GITHUB_HEAD_REF}` outputs the correct branch name instead of something like `refs_pull_120_merge`.
> chore(dx): run prerelease task only when pr is ready for review

- packages/studio-ui/src/web/views/FlowBuilder/diagram/nodes/Components/style.scss
Not in my linear tasks but a tiny visual bug fix.
Before 
https://user-images.githubusercontent.com/159949/146086294-12bb7a2a-3163-4a0c-a910-bf4630176309.mov
After
https://user-images.githubusercontent.com/159949/146086303-c4b5a558-48a7-49dd-93ba-6842f0686dd9.mov
> fix(flow): tiny z-index css fix on flow editor

- packages/studio-ui/src/web/actions/index.ts
- packages/studio-ui/src/web/reducers/flows.ts
- packages/studio-ui/src/web/util/flows.ts
Copying a skill node does a shallow copy, creates a new node linked to same skill
Copying a skill node creates a clone of the skill, creates a new node linked to clone, but keeps shallow reference to CMS content in skill
---
This behavior was determined to be the most predictable for current users.
> fix(copy): copying skill makes clone but uses same cms content

- packages/studio-be/src/core/dialog/flow/flow-service.ts
This PR goes hand in hand with https://github.com/botpress/botpress/pull/5771
Prevent creating or renaming a flow with an already existing flow name. Case insensitive.
> chore(flow): prevent using same flow name

- packages/studio-be/src/sdk/botpress.d.ts
- packages/studio-ui/src/web/views/FlowBuilder/nodeProps/ActionModalForm.tsx
Hide module actions on cloud-enabled bots because they're not supported on the cloud yet
> fix(actions): hide module actions on cloud-enabled bots

- .github/workflows/branch_deleted.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
This PR makes sure we use the v1 of our custom actions from botpress/gh-actions. This allows us to potentially push breaking changes on master without ever impacting actions that currently depend on them.
Similar to what has been done here: https://github.com/botpress/botpress/pull/11211
> chore(ci_cd): use gh-actions v1

- packages/studio-ui/src/web/views/FlowBuilder/sidePanelFlows/FlowNameModal.tsx
When fixing DEV-1425, forgot to handle all possible casings for the skills folder.
> fix(studio): prevent skills folder with casing

- .github/workflows/pre-release.yml
I brought changes from next branch. This essentially makes sure that when we update a PR (for instance master <-- next) the head binaries get update. This way, anyone working on the next branch of botpress/botpress will have the latest changes without needing to run studio from source.
> chore(dev): update pre-release binaries on pr update

- packages/studio-be/src/core/app/server.ts
When a file is not found in the studio assets, it forwards the request to the core, which then re-directs it back to the studio... This happens during like 30 seconds, then it fails the request. 
The fix is simple. if the file is not found, it just stops there.
> fix(studio): prevent back & forth when file is not found

- packages/studio-ui/src/web/components/Layout/StatusBar/LangSwitcher.tsx
Fix a random error which happens sometimes with slower connections. Someone one call takes longer, and the lang switcher mounts, then unmounts, then remounts, but since it changed the value to null when unmounting, it crashed the studio.
Quick & dirty fix. Eventually we'll get rid of react-bootstrap once and for all
> fix(studio): fix random error with lang switcher

- packages/studio-be/src/studio/nlu/bot/index.ts
If you try training a chatbot that has an intent with no utterances, it crashes the studio.
This regression was introduced by me here: https://github.com/botpress/studio/pull/255
This PR fixes it, and make sure the error is displayed in the UI
> fix(nlu): correctly display error if training fails before it starts

- packages/studio-be/src/builtin/bot-templates/learn-botpress/bot.config.json
Well this is pretty self explanatory.
Before
After: 
closes : BUS-195
> fix(builtin): add missing template name

- packages/studio-ui/src/web/components/ContentForm/UploadWidget/UrlUpload.tsx
- packages/studio-ui/src/web/components/ContentForm/UploadWidget/index.tsx
The references to the content types translation module were wrong. I used the right ones.
> fix(translation): fix contentTypes translation references

- packages/studio-be/package.json
- yarn.lock
This PR fixes an issue with the binary produced with `pkg`. Since pkg uses fs-extra v8, it conflicted, when running the binary, with the version (v10) that was installed in the `studio-be` package.
Related to: https://github.com/vercel/pkg/issues/1180
Closes BUS-214
> revert(deps): downgrade fs-extra to v9

- packages/superinput/demo/app.tsx
- packages/superinput/src/EvalPanel.tsx
- packages/superinput/src/SuperInput.tsx
- packages/superinput/src/index.scss
> fix(superinput): various ux bugs

- packages/studio-ui/src/web/views/Nlu/intents/style.scss
- packages/studio-ui/src/web/views/Nlu/intents/style.scss.d.ts
Slot panel resize was fixed in #295 but this makes some minor improvements to slot panel UI on smaller screen sizes.
Before
After
https://user-images.githubusercontent.com/159949/154968810-58217465-4afb-4bd7-8e90-9226b24aacde.mov
> fix(qna): improve slot intent sidebar ui

- package.json
- scripts/package.ts
Packaging failed on windows because of the command not including cross-env.
Also made a small adjustment to the package.json file, scripts should do a single task... Package shouldn't clean/build/package, it just packages. If those commands must be used together, then they must be typed independently
> fix(build): fix package on windows & cmd

- packages/studio-ui/src/web/reducers/ui.ts
- packages/studio-ui/src/web/views/FlowBuilder/index.tsx
The explorer (left side panel) was hidden by default for the 1st time you open studio. This little change fixes it
> fix(ui): display explorer by default

- packages/studio-be/src/builtin/content-types/card.ts
- packages/studio-ui/src/web/translations/en.json
- packages/studio-ui/src/web/translations/es.json
- packages/studio-ui/src/web/translations/fr.json
Since the json schema is generated for each new chatbot in its content-type folder, we would need a file migration in order to get that fix for existing chatbots. If we want to go that route this needs to be addressed in another pull request. Meanwhile these little changes fixes it for newly created chatbots.
Before: 
After
> fix(content): added translations for card buttons

- package.json
This PR fixes an issue where typings were not included in the binary version of the studio resulting in files not found error when trying to load the typings.
Closes DEV-2383
> fix(server): fix loading typings when running bin version

- packages/studio-be/src/builtin/actions/basic-skills/slot_update_contexts.js
This is my second attempt at fixing DEV-2361. My first attempt was [in this PR](https://github.com/botpress/studio/pull/300).
What happened is:
- The routes where moved to the studio
- So my fix was to call the new location instead of the old one
- But now that I think about it, is it impossible for an action that runs on the cloud to call the studio
- So I replaced the axios call by reading the ghost directly
I don't consider this fix "pretty" or "sexy", but it works and it's good enough
> fix(builtin): slot update context now works without need for studio

- packages/studio-be/src/studio/libraries/libraries-router.ts
- packages/studio-be/src/studio/libraries/libraries-service.ts
- packages/studio-ui/src/web/views/Libraries/AddLibrary.tsx
This fixes two issues with the libraries on the studio:
1. Adding a lib would crash the studio (happened with packages starting with an @)
2. Search wasn't working with packages including a slash
> fix(studio): fix libraries

- packages/studio-be/src/studio/internal-router.ts
This PR adds a route that allows Botpess to invalidate the Studio's CMS cache for a given bot ID.
Related PR: https://github.com/botpress/botpress/pull/11631
> chore(studio-be): add route to invalidate cms cache for bot

- packages/studio-ui/src/web/views/CodeEditor/components/NewFileModal.tsx
Slight change I had to do, if you created a file without adding .js in the modal, it would not add the template. Logic is identical from the module
> fix(code-editor): slight adjustment

- packages/studio-be/src/core/app/core-client.ts
- packages/studio-be/src/core/bots/bot-service.ts
This PR fixes an issue where unmounting or mounting a bot using the bot config page would not trigger `after_bot_mount` and `after_bot_unmount` hooks. The reason was that the core was never aware of this change. To fix the issue, we simply send an internal call to the core telling it to unmount/mount a certain bot.
Closes https://github.com/botpress/botpress/issues/11601
Related to:
> fix(hooks): send events to core on bot mount and unmount

- packages/studio-be/package.json
- packages/studio-be/src/core/bots/bot-service.ts
- packages/studio-be/src/studio/cloud/cloud-router.ts
- packages/studio-be/src/studio/nlu/bot/index.ts
- packages/studio-be/src/studio/nlu/nlu-client/cloud/client.ts
- packages/studio-be/src/studio/nlu/nlu-client/index.ts
- packages/studio-be/src/studio/nlu/nlu-service.ts
- yarn.lock
This PR adds the prerequisites steps to make sure that the models are uploaded with the chatbot when deploying to the cloud.
1. Use the cloud NLU
- No configuration is required
- It will succeed and you will be able to see the model(s) on the disk under `data/<botId>/models/<modelId>`
3. Run the NLU locally 
- Clone the NLU repository and checkout the `cloud` branch
- Set `CLOUD_NLU_ENDPOINT` to `http://localhost3200` on Botpress side
- Create a configuration file for the NLU server by running `yarn start init`
- Edit the `nlu.config.json` file by adding the config `"modelTransferEnabled": true`
- Start the NLU server and try to deploy a bot. It will fail but you will be able to see the model(s) on the disk under `data/<botId>/models/<modelId>`
> feat(studio): add download modelweights step before uploading chatbot to cloud

- packages/studio-ui/src/web/components/Layout/BottomPanel/Logs/index.tsx
This PR adds the logic to handle displaying raw user data when possible. 
The thumb rule is basic, don't escape characters that aren't escaped by the channel-web or the console.
**Before**
**After**
Closes https://github.com/botpress/botpress/issues/11271
> fix(debugger): do not escape user input in debugger logs

- packages/studio-be/src/common/code-editor.ts
This PR adds the possibility to create a hook with the name of the hook type. Before this change, the resulting filename would be .js since we were removing the hook type from its name (not sure why as there seems to be no impact of doing so).
e.g. Creating an after_incoming_middleware hook named: after_incoming_middleware.js
Same changes as this PR: https://github.com/botpress/botpress/pull/11698
> fix(code-editor): allow creating hooks with hook type as name

- packages/studio-ui/src/web/views/Qna/index.tsx
This little change fixes the infinite scroll which was broken for bots having more than 50 qnas.
closes DEV-2625
closes https://github.com/botpress/studio/issues/348
> fix(qna): infinite scroll

- packages/ui-shared/package.json
- packages/ui-shared/src/translations/en.json
- packages/ui-shared/src/translations/es.json
- packages/ui-shared/src/translations/fr.json
- packages/ui-shared/src/translations/index.tsx
- yarn.lock
I simply use a library instead of managing all language code manually. Notice that I "hijacked" the `tr` function so it is supported everywhere we use it without breaking the usage.
We can also make the same change in the admin code at some point
Little sign of ❤️ to @sebburon
> chore(ui): add support for all iso language code

- packages/studio-ui/src/web/views/FlowBuilder/sidePanelFlows/util.tsx
pretty self explanatory
fixes this:
> fix(ui): wrong translation keys in file explorer

- packages/studio-be/src/core/security/router-security.ts
- packages/studio-be/src/core/users/workspace-service.ts
This simple PR ensures that a user really has access to a bot targeted by a request. Before this change, a user could perform some actions on a chatbot from a foreign workspace.
> fix(security): validate bot access

- package.json
- packages/studio-be/api.rest
- packages/studio-be/src/core/app/server.ts
- packages/studio-be/src/studio/studio-router.ts
- packages/studio-ui/src/web/index.html
This PR fixes an issue where when the JWT token was stored in the cookie storage, the call to `/env` would fail with a 401. The request was denied because the `window` variable '`USE_JWT_COOKIES`' was not set at this point.
To fix the problem, I renamed the `/branding.js` call to `/public-env.js` so that we can send any **public** environment variable to the front-end without authentication and passed the value of `process.USE_JWT_COOKIES` in it.
> fix(auth): fix authenticating with cookie storage

- packages/studio-ui/src/web/components/Layout/BottomPanel/Logs/index.tsx
This PR fixes the display of the date in the studio's debugger.
**before**
**after**
> fix(debugger): fix display of log timestamp

- packages/studio-be/src/core/security/router-security.ts
This PR fixes an issue where unmounting a bot would prevent the user from accessing the bot settings page.
The issue came from the `checkBotVisibility` middleware that checks whether or not the bot is accessible (mounted). It contains an exception for the `/env` route and placeholder bots (`___`). Meaning that we were missing the exception for the `public-env` route.
> fix(security): fix access to public envs when bot is unmounted

- packages/studio-be/src/core/dialog/skill-service.ts
- packages/studio-be/src/sdk/botpress.d.ts
- packages/studio-ui/src/web/reducers/flows.ts
- packages/studio-ui/src/web/views/FlowBuilder/diagram/manager.ts
- packages/studio-ui/src/web/views/FlowBuilder/diagram/nodes/Block/index.tsx
- packages/studio-ui/src/web/views/FlowBuilder/diagram/nodes/SkillCallContents/index.tsx
- packages/studio-ui/src/web/views/FlowBuilder/skills/index.jsx
This feature allows the flow generator to return a list of content elements to be previewed in the flow editor.
Example: 
The content element ids are saved in the node definition (same logic as transitions)
It can be specified in the flow generator function in the return object.
> feat(studio): preview content elements from skills

- packages/studio-ui/src/web/views/FlowBuilder/common/ActionItem.tsx
- packages/studio-ui/src/web/views/FlowBuilder/common/style.scss
> fix(studio): fix img renderer for node preview

- package.json
This PR fixes an issue where in some cases, not deleting the out folder in the backend would result in deleted files being resolved.
> chore(dx): clean out folders before building

- packages/studio-ui/package.json
- packages/studio-ui/src/web/views/Nlu/intents/UtterancesEditor.tsx
- packages/studio-ui/src/web/views/Nlu/intents/style.scss
- packages/studio-ui/src/web/views/Nlu/intents/style.scss.d.ts
- yarn.lock
This fixes an issue with the utterances editor on the latest version of Chromium and related browsers
Before:
https://user-images.githubusercontent.com/13484138/191140116-6ad37f11-291f-4341-980c-213dbe70eb0d.mp4
After:
https://user-images.githubusercontent.com/13484138/191140132-c45b0043-000d-426b-86e8-c9c18815e880.mp4
I Fixed it by reimplementing the faulty plugin, which caused the bug
> fix(studio): fix NLU utterances placeholder on Chromium

- packages/studio-ui/src/web/views/Nlu/intents/style.scss
Pretty simple fix, clicking on the placeholder will also focus on the input field
Related: https://github.com/botpress/botpress/discussions/12162#discussioncomment-3934730
> fix(studio): click on placeholder will focus on input field

- packages/studio-ui/src/web/actions/index.ts
- packages/studio-ui/src/web/components/Content/Select/index.tsx
This PR fixes 2 issues that are mentioned [here](https://github.com/botpress/botpress/discussions/12141#discussioncomment-3939768)
1- It prevent to fetch invalid or undefined content element (the issue causing the 504)
2- Properly initializes the content type selector form when the category is already defined. (Issue is coming from the fact that I brought this piece of code from cloud studio which has a different behavior)
**before: forever spinning wheel**
**before: create or select content item=**
> fix: properly set content type form step

- packages/studio-ui/src/web/views/FlowBuilder/common/style.scss
While fixing another issue, I had this very annoying overflow behaviour where very long content elements would overflow out of the drag n drop section and causing a hover flicker.
**Before**:
**After**:
> fix(ui): prevent long content type to overflow

- packages/studio-ui/src/web/views/FlowBuilder/common/DraggableNodeItem.tsx
Pretty simple and straight forward. This simple change allows a user to edit a node item by double clicking a draggable node item. One liner time saver for all bot builders
> feat: double click on draggable item to edit

- packages/studio-ui/src/web/components/Layout/Toolbar/index.tsx
- packages/studio-ui/src/web/translations/en.json
As requested on https://linear.app/botpress/issue/GTM-309/add-buttons-to-v12-to-make-it-easier-for-users-to-get-help-in-the-v12 we added a Help button on the studio
> feat(studio): add help button
